function upV(){if(gn)gn.gain.value=$('vl').value*0.5}
function sync(s){if(exMd==='mock'&&mkPh!==0)return;const w=parseFloat($('wc').value),m=au.duration/60;if(!m||!w)return;if(s==='w'){$('ri').value=(parseFloat($('wi').value)/(w/m)).toFixed(4);au.playbackRate=Math.max(0.1,parseFloat($('ri').value))}else{const wpm=((w/m)*parseFloat($('ri').value));$('wi').value=wpm.toFixed(2);au.playbackRate=Math.max(0.1,parseFloat($('ri').value))}
const sel=$('ws'),val=$('wi').value,opts=Array.from(sel.options).map(o=>o.value);if(!opts.includes(val)){let o=document.createElement('option');o.value=val;o.text=Math.round(val);sel.add(o);sel.value=val}
const rSel=$('rs'),rVal=$('ri').value,rOpts=Array.from(rSel.options).map(o=>o.value);if(!rOpts.includes(rVal)){let o=document.createElement('option');o.value=rVal;o.text=rVal;rSel.add(o);rSel.value=rVal}
updateStatus();svSt()}
function dS(k,v){if(!v)return;if(k==='w')$('wi').value=v;else $('ri').value=v}
function adW(d){$('wi').value=(parseFloat($('wi').value||0)+d).toFixed(2);sync('w')}
function adR(d){$('ri').value=(parseFloat($('ri').value||1)+d).toFixed(4);sync('r')}
function updatePlBtn(){$('pl').innerHTML=is?'<svg viewBox="0 0 24 24"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>':'<svg viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>';if(is)$('pl').classList.add('pausing');else $('pl').classList.remove('pausing')}
async function beeps(s){const gv=$('vl').value*0.25;for(let i=0;i<5;i++){if(s.aborted)return;const o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.connect(g);g.connect(ac.destination);g.gain.value=gv;o.frequency.value=i===4?880:440;o.start();o.stop(ac.currentTime+0.1);await new Promise(r=>setTimeout(r,1000))}}
function sk(s){if(exMd==='mock')return;au.currentTime+=s*(parseFloat($('ri').value)||1)}
async function expA(){const b=$('exB'),r=parseFloat($('ri').value);b.innerText='⌛';if($('tx').value){const tb=new Blob([$('tx').value],{type:'text/plain'}),ta=document.createElement('a');ta.href=URL.createObjectURL(tb);ta.download='Transcription.txt';ta.click()}if(r===1.0){const a=document.createElement('a');a.href=au.src;a.download='Audio.mp3';a.click();b.innerText='⬇️';return}try{const res=await fetch(au.src),buf=await res.arrayBuffer(),ctx=new OfflineAudioContext(2,buf.byteLength/r,44100),sBuf=await ctx.decodeAudioData(buf),src=ctx.createBufferSource();src.buffer=sBuf;src.playbackRate.value=r;src.connect(ctx.destination);src.start();const ren=await ctx.startRendering(),blob=new Blob([toWav(ren)],{type:'audio/wav'}),name=`WPM${Math.round($('wi').value)}`;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.wav';a.click()}catch(e){}finally{b.innerText='⬇️'}}
function toWav(b){let n=b.numberOfChannels,len=b.length*n*2+44,buf=new ArrayBuffer(len),v=new DataView(buf),pos=44;const s=(st,s)=>{for(let i=0;i<s.length;i++)v.setUint8(st+i,s.charCodeAt(i))};s(0,'RIFF');v.setUint32(4,len-8,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,n,true);v.setUint32(24,b.sampleRate,true);v.setUint32(28,b.sampleRate*n*2,true);v.setUint16(32,n*2,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,len-44,true);for(let i=0;i<b.length;i++)for(let c=0;c<n;c++){let x=Math.max(-1,Math.min(1,b.getChannelData(c)[i]));v.setInt16(pos,x<0?x*0x8000:x*0x7FFF,true);pos+=2}return buf}